#include "instructions.h"

// TODO: Decide implementation of instructions

Instruction instructions[0x100] = {
    [0x00] = {INS_NOP, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x01] = {INS_LD, AM_R_D16, BC, NONE, CT_NONE, 0},
    [0x02] = {INS_LD, AM_MR_R, BC, A, CT_NONE, 0},
    [0x03] = {INS_INC, AM_R, BC, NONE, CT_NONE, 0},
    [0x04] = {INS_INC, AM_R, B, NONE, CT_NONE, 0},
    [0x05] = {INS_DEC, AM_R, B, NONE, CT_NONE, 0},
    [0x06] = {INS_LD, AM_R_D8, B, NONE, CT_NONE, 0},
    [0x07] = {INS_RLCA, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x08] = {INS_LD, AM_A16_R, NONE, SP, CT_NONE, 0},
    [0x09] = {INS_ADD, AM_R_R, HL, BC, CT_NONE, 0},
    [0x0A] = {INS_LD, AM_R_MR, A, BC, CT_NONE, 0},
    [0x0B] = {INS_DEC, AM_R, BC, NONE, CT_NONE, 0},
    [0x0C] = {INS_INC, AM_R, C, NONE, CT_NONE, 0},
    [0x0D] = {INS_DEC, AM_R, C, NONE, CT_NONE, 0},
    [0x0E] = {INS_LD, AM_R_D8, C, NONE, CT_NONE, 0},
    [0x0F] = {INS_RRCA, AM_IMP, NONE, NONE, CT_NONE, 0},

    [0x10] = {INS_STOP, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x11] = {INS_LD, AM_R_D16, DE, NONE, CT_NONE, 0},
    [0x12] = {INS_LD, AM_MR_R, DE, A, CT_NONE, 0},
    [0x13] = {INS_INC, AM_R, DE, NONE, CT_NONE, 0},
    [0x14] = {INS_INC, AM_R, D, NONE, CT_NONE, 0},
    [0x15] = {INS_DEC, AM_R, D, NONE, CT_NONE, 0},
    [0x16] = {INS_LD, AM_R_D8, D, NONE, CT_NONE, 0},
    [0x17] = {INS_RLA, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x18] = {INS_JR, AM_D8, NONE, NONE, CT_NONE, 0},
    [0x19] = {INS_ADD, AM_R_R, HL, DE, CT_NONE, 0},
    [0x1A] = {INS_LD, AM_R_MR, A, DE, CT_NONE, 0},
    [0x1B] = {INS_DEC, AM_R, DE, NONE, CT_NONE, 0},
    [0x1C] = {INS_INC, AM_R, E, NONE, CT_NONE, 0},
    [0x1D] = {INS_DEC, AM_R, E, NONE, CT_NONE, 0},
    [0x1E] = {INS_LD, AM_R_D8, E, NONE, CT_NONE, 0},
    [0x1F] = {INS_RRA, AM_IMP, NONE, NONE, CT_NONE, 0},

    [0x20] = {INS_JR, AM_D8, NONE, NONE, CT_NZ, 0},
    [0x21] = {INS_LD, AM_R_D16, HL, NONE, CT_NONE, 0},
    [0x22] = {INS_LD, AM_HLI_R, HL, A},
    [0x23] = {INS_INC, AM_R, HL},
    [0x24] = {INS_INC, AM_R, H},
    [0x25] = {INS_DEC, AM_R, H},
    [0x26] = {INS_LD, AM_R_D8, H},
    [0x27] = {INS_DAA},
    [0x28] = {INS_JR, AM_D8, NONE, NONE, CT_Z},
    [0x29] = {INS_ADD, AM_R_R, HL, HL},
    [0x2A] = {INS_LD, AM_R_HLI, A, HL},
    [0x2B] = {INS_DEC, AM_R, HL},
    [0x2C] = {INS_INC, AM_R, L},
    [0x2D] = {INS_DEC, AM_R, L},
    [0x2E] = {INS_LD, AM_R_D8, L},
    [0x2F] = {INS_CPL},
};