#include "instructions.h"
#include "cpu.h"

Instruction instructions[0x100] = {
    [0x00] = {INS_NOP, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x01] = {INS_LD, AM_R_D16, BC, NONE, CT_NONE, 0},
    [0x02] = {INS_LD, AM_MR_R, BC, A, CT_NONE, 0},
    [0x03] = {INS_INC, AM_R, BC, NONE, CT_NONE, 0},
    [0x04] = {INS_INC, AM_R, B, NONE, CT_NONE, 0},
    [0x05] = {INS_DEC, AM_R, B, NONE, CT_NONE, 0},
    [0x06] = {INS_LD, AM_R_D8, B, NONE, CT_NONE, 0},
    [0x07] = {INS_RLCA, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x08] = {INS_LD, AM_A16_R, NONE, SP, CT_NONE, 0},
    [0x09] = {INS_ADD, AM_R_R, HL, BC, CT_NONE, 0},
    [0x0A] = {INS_LD, AM_R_MR, A, BC, CT_NONE, 0},
    [0x0B] = {INS_DEC, AM_R, BC, NONE, CT_NONE, 0},
    [0x0C] = {INS_INC, AM_R, C, NONE, CT_NONE, 0},
    [0x0D] = {INS_DEC, AM_R, C, NONE, CT_NONE, 0},
    [0x0E] = {INS_LD, AM_R_D8, C, NONE, CT_NONE, 0},
    [0x0F] = {INS_RRCA, AM_IMP, NONE, NONE, CT_NONE, 0},

    [0x10] = {INS_STOP, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x11] = {INS_LD, AM_R_D16, DE, NONE, CT_NONE, 0},
    [0x12] = {INS_LD, AM_MR_R, DE, A, CT_NONE, 0},
    [0x13] = {INS_INC, AM_R, DE, NONE, CT_NONE, 0},
    [0x14] = {INS_INC, AM_R, D, NONE, CT_NONE, 0},
    [0x15] = {INS_DEC, AM_R, D, NONE, CT_NONE, 0},
    [0x16] = {INS_LD, AM_R_D8, D, NONE, CT_NONE, 0},
    [0x17] = {INS_RLA, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x18] = {INS_JR, AM_D8, NONE, NONE, CT_NONE, 0},
    [0x19] = {INS_ADD, AM_R_R, HL, DE, CT_NONE, 0},
    [0x1A] = {INS_LD, AM_R_MR, A, DE, CT_NONE, 0},
    [0x1B] = {INS_DEC, AM_R, DE, NONE, CT_NONE, 0},
    [0x1C] = {INS_INC, AM_R, E, NONE, CT_NONE, 0},
    [0x1D] = {INS_DEC, AM_R, E, NONE, CT_NONE, 0},
    [0x1E] = {INS_LD, AM_R_D8, E, NONE, CT_NONE, 0},
    [0x1F] = {INS_RRA, AM_IMP, NONE, NONE, CT_NONE, 0},

    [0x20] = {INS_JR, AM_D8, NONE, NONE, CT_NZ, 0},
    [0x21] = {INS_LD, AM_R_D16, HL, NONE, CT_NONE, 0},
    [0x22] = {INS_LD, AM_HLI_R, HL, A, CT_NONE, 0},
    [0x23] = {INS_INC, AM_R, HL, NONE, CT_NONE, 0},
    [0x24] = {INS_INC, AM_R, H, NONE, CT_NONE, 0},
    [0x25] = {INS_DEC, AM_R, H, NONE, CT_NONE, 0},
    [0x26] = {INS_LD, AM_R_D8, H, NONE, CT_NONE, 0},
    [0x27] = {INS_DAA, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x28] = {INS_JR, AM_D8, NONE, NONE, CT_Z, 0},
    [0x29] = {INS_ADD, AM_R_R, HL, HL, CT_NONE, 0},
    [0x2A] = {INS_LD, AM_R_HLI, A, HL, CT_NONE, 0},
    [0x2B] = {INS_DEC, AM_R, HL, NONE, CT_NONE, 0},
    [0x2C] = {INS_INC, AM_R, L, NONE, CT_NONE, 0},
    [0x2D] = {INS_DEC, AM_R, L, NONE, CT_NONE, 0},
    [0x2E] = {INS_LD, AM_R_D8, L, NONE, CT_NONE, 0},
    [0x2F] = {INS_CPL, AM_IMP, NONE, NONE, CT_NONE, 0},

    [0x30] = {INS_JR, AM_D8, NONE, NONE, CT_NC, 0},
    [0x31] = {INS_LD, AM_R_D16, SP, NONE, CT_NONE, 0},
    [0x32] = {INS_LD, AM_HLD_R, HL, A, CT_NONE, 0},
    [0x33] = {INS_INC, AM_R, SP, NONE, CT_NONE, 0},
    [0x34] = {INS_INC, AM_MR, HL, NONE, CT_NONE, 0},
    [0x35] = {INS_DEC, AM_MR, HL, NONE, CT_NONE, 0},
    [0x36] = {INS_LD, AM_MR_D8, HL, NONE, CT_NONE, 0},
    [0x37] = {INS_SCF, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x38] = {INS_JR, AM_D8, NONE, NONE, CT_C, 0},
    [0x39] = {INS_ADD, AM_R_R, HL, SP, CT_NONE, 0},
    [0x3A] = {INS_LD, AM_R_HLD, A, HL, CT_NONE, 0},
    [0x3B] = {INS_DEC, AM_R, SP, NONE, CT_NONE, 0},
    [0x3C] = {INS_INC, AM_R, A, NONE, CT_NONE, 0},
    [0x3D] = {INS_DEC, AM_R, A, NONE, CT_NONE, 0},
    [0x3E] = {INS_LD, AM_R_D8, A, NONE, CT_NONE, 0},
    [0x3F] = {INS_CCF, AM_IMP, NONE, NONE, CT_NONE, 0},

    [0x40] = {INS_LD, AM_R_R, B, B, CT_NONE, 0},
    [0x41] = {INS_LD, AM_R_R, B, C, CT_NONE, 0},
    [0x42] = {INS_LD, AM_R_R, B, D, CT_NONE, 0},
    [0x43] = {INS_LD, AM_R_R, B, E, CT_NONE, 0},
    [0x44] = {INS_LD, AM_R_R, B, H, CT_NONE, 0},
    [0x45] = {INS_LD, AM_R_R, B, L, CT_NONE, 0},
    [0x46] = {INS_LD, AM_R_MR, B, HL, CT_NONE, 0},
    [0x47] = {INS_LD, AM_R_R, B, A, CT_NONE, 0},
    [0x48] = {INS_LD, AM_R_R, C, B, CT_NONE, 0},
    [0x49] = {INS_LD, AM_R_R, C, C, CT_NONE, 0},
    [0x4A] = {INS_LD, AM_R_R, C, D, CT_NONE, 0},
    [0x4B] = {INS_LD, AM_R_R, C, E, CT_NONE, 0},
    [0x4C] = {INS_LD, AM_R_R, C, H, CT_NONE, 0},
    [0x4D] = {INS_LD, AM_R_R, C, L, CT_NONE, 0},
    [0x4E] = {INS_LD, AM_R_MR, C, HL, CT_NONE, 0},
    [0x4F] = {INS_LD, AM_R_R, C, A, CT_NONE, 0},

    [0x50] = {INS_LD, AM_R_R,  D, B, CT_NONE, 0},
    [0x51] = {INS_LD, AM_R_R,  D, C, CT_NONE, 0},
    [0x52] = {INS_LD, AM_R_R,  D, D, CT_NONE, 0},
    [0x53] = {INS_LD, AM_R_R,  D, E, CT_NONE, 0},
    [0x54] = {INS_LD, AM_R_R,  D, H, CT_NONE, 0},
    [0x55] = {INS_LD, AM_R_R,  D, L, CT_NONE, 0},
    [0x56] = {INS_LD, AM_R_MR, D, HL, CT_NONE, 0},
    [0x57] = {INS_LD, AM_R_R,  D, A, CT_NONE, 0},
    [0x58] = {INS_LD, AM_R_R,  E, B, CT_NONE, 0},
    [0x59] = {INS_LD, AM_R_R,  E, C, CT_NONE, 0},
    [0x5A] = {INS_LD, AM_R_R,  E, D, CT_NONE, 0},
    [0x5B] = {INS_LD, AM_R_R,  E, E, CT_NONE, 0},
    [0x5C] = {INS_LD, AM_R_R,  E, H, CT_NONE, 0},
    [0x5D] = {INS_LD, AM_R_R,  E, L, CT_NONE, 0},
    [0x5E] = {INS_LD, AM_R_MR, E, HL, CT_NONE, 0},
    [0x5F] = {INS_LD, AM_R_R,  E, A, CT_NONE, 0},

    [0x60] = {INS_LD, AM_R_R,  H, B, CT_NONE, 0},
    [0x61] = {INS_LD, AM_R_R,  H, C, CT_NONE, 0},
    [0x62] = {INS_LD, AM_R_R,  H, D, CT_NONE, 0},
    [0x63] = {INS_LD, AM_R_R,  H, E, CT_NONE, 0},
    [0x64] = {INS_LD, AM_R_R,  H, H, CT_NONE, 0},
    [0x65] = {INS_LD, AM_R_R,  H, L, CT_NONE, 0},
    [0x66] = {INS_LD, AM_R_MR, H, HL, CT_NONE, 0},
    [0x67] = {INS_LD, AM_R_R,  H, A, CT_NONE, 0},
    [0x68] = {INS_LD, AM_R_R,  L, B, CT_NONE, 0},
    [0x69] = {INS_LD, AM_R_R,  L, C, CT_NONE, 0},
    [0x6A] = {INS_LD, AM_R_R,  L, D, CT_NONE, 0},
    [0x6B] = {INS_LD, AM_R_R,  L, E, CT_NONE, 0},
    [0x6C] = {INS_LD, AM_R_R,  L, H, CT_NONE, 0},
    [0x6D] = {INS_LD, AM_R_R,  L, L, CT_NONE, 0},
    [0x6E] = {INS_LD, AM_R_MR, L, HL, CT_NONE, 0},
    [0x6F] = {INS_LD, AM_R_R,  L, A, CT_NONE, 0},

    [0x70] = {INS_LD, AM_MR_R,  HL, B, CT_NONE, 0},
    [0x71] = {INS_LD, AM_MR_R,  HL, C, CT_NONE, 0},
    [0x72] = {INS_LD, AM_MR_R,  HL, D, CT_NONE, 0},
    [0x73] = {INS_LD, AM_MR_R,  HL, E, CT_NONE, 0},
    [0x74] = {INS_LD, AM_MR_R,  HL, H, CT_NONE, 0},
    [0x75] = {INS_LD, AM_MR_R,  HL, L, CT_NONE, 0},
    [0x76] = {INS_HALT, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0x77] = {INS_LD, AM_MR_R,  HL, A, CT_NONE, 0},
    [0x78] = {INS_LD, AM_R_R,  A, B, CT_NONE, 0},
    [0x79] = {INS_LD, AM_R_R,  A, C, CT_NONE, 0},
    [0x7A] = {INS_LD, AM_R_R,  A, D, CT_NONE, 0},
    [0x7B] = {INS_LD, AM_R_R,  A, E, CT_NONE, 0},
    [0x7C] = {INS_LD, AM_R_R,  A, H, CT_NONE, 0},
    [0x7D] = {INS_LD, AM_R_R,  A, L, CT_NONE, 0},
    [0x7E] = {INS_LD, AM_R_MR, A, HL, CT_NONE, 0},
    [0x7F] = {INS_LD, AM_R_R,  A, A, CT_NONE, 0},

    [0x80] = {INS_ADD, AM_R_R, A, B, CT_NONE, 0},
    [0x81] = {INS_ADD, AM_R_R, A, C, CT_NONE, 0},
    [0x82] = {INS_ADD, AM_R_R, A, D, CT_NONE, 0},
    [0x83] = {INS_ADD, AM_R_R, A, E, CT_NONE, 0},
    [0x84] = {INS_ADD, AM_R_R, A, H, CT_NONE, 0},
    [0x85] = {INS_ADD, AM_R_R, A, L, CT_NONE, 0},
    [0x86] = {INS_ADD, AM_R_MR, A, HL, CT_NONE, 0},
    [0x87] = {INS_ADD, AM_R_R, A, A, CT_NONE, 0},
    [0x88] = {INS_ADC, AM_R_R, A, B, CT_NONE, 0},
    [0x89] = {INS_ADC, AM_R_R, A, C, CT_NONE, 0},
    [0x8A] = {INS_ADC, AM_R_R, A, D, CT_NONE, 0},
    [0x8B] = {INS_ADC, AM_R_R, A, E, CT_NONE, 0},
    [0x8C] = {INS_ADC, AM_R_R, A, H, CT_NONE, 0},
    [0x8D] = {INS_ADC, AM_R_R, A, L, CT_NONE, 0},
    [0x8E] = {INS_ADC, AM_R_MR, A, HL, CT_NONE, 0},
    [0x8F] = {INS_ADC, AM_R_R, A, A, CT_NONE, 0},

    [0x90] = {INS_SUB, AM_R_R, A, B, CT_NONE, 0},
    [0x91] = {INS_SUB, AM_R_R, A, C, CT_NONE, 0},
    [0x92] = {INS_SUB, AM_R_R, A, D, CT_NONE, 0},
    [0x93] = {INS_SUB, AM_R_R, A, E, CT_NONE, 0},
    [0x94] = {INS_SUB, AM_R_R, A, H, CT_NONE, 0},
    [0x95] = {INS_SUB, AM_R_R, A, L, CT_NONE, 0},
    [0x96] = {INS_SUB, AM_R_MR, A, HL, CT_NONE, 0},
    [0x97] = {INS_SUB, AM_R_R, A, A, CT_NONE, 0},
    [0x98] = {INS_SBC, AM_R_R, A, B, CT_NONE, 0},
    [0x99] = {INS_SBC, AM_R_R, A, C, CT_NONE, 0},
    [0x9A] = {INS_SBC, AM_R_R, A, D, CT_NONE, 0},
    [0x9B] = {INS_SBC, AM_R_R, A, E, CT_NONE, 0},
    [0x9C] = {INS_SBC, AM_R_R, A, H, CT_NONE, 0},
    [0x9D] = {INS_SBC, AM_R_R, A, L, CT_NONE, 0},
    [0x9E] = {INS_SBC, AM_R_MR, A, HL, CT_NONE, 0},
    [0x9F] = {INS_SBC, AM_R_R, A, A, CT_NONE, 0},

    [0xA0] = {INS_AND, AM_R_R, A, B, CT_NONE, 0},
    [0xA1] = {INS_AND, AM_R_R, A, C, CT_NONE, 0},
    [0xA2] = {INS_AND, AM_R_R, A, D, CT_NONE, 0},
    [0xA3] = {INS_AND, AM_R_R, A, E, CT_NONE, 0},
    [0xA4] = {INS_AND, AM_R_R, A, H, CT_NONE, 0},
    [0xA5] = {INS_AND, AM_R_R, A, L, CT_NONE, 0},
    [0xA6] = {INS_AND, AM_R_MR, A, HL, CT_NONE, 0},
    [0xA7] = {INS_AND, AM_R_R, A, A, CT_NONE, 0},
    [0xA8] = {INS_XOR, AM_R_R, A, B, CT_NONE, 0},
    [0xA9] = {INS_XOR, AM_R_R, A, C, CT_NONE, 0},
    [0xAA] = {INS_XOR, AM_R_R, A, D, CT_NONE, 0},
    [0xAB] = {INS_XOR, AM_R_R, A, E, CT_NONE, 0},
    [0xAC] = {INS_XOR, AM_R_R, A, H, CT_NONE, 0},
    [0xAD] = {INS_XOR, AM_R_R, A, L, CT_NONE, 0},
    [0xAE] = {INS_XOR, AM_R_MR, A, HL, CT_NONE, 0},
    [0xAF] = {INS_XOR, AM_R_R, A, A, CT_NONE, 0},

    [0xB0] = {INS_OR, AM_R_R, A, B, CT_NONE, 0},
    [0xB1] = {INS_OR, AM_R_R, A, C, CT_NONE, 0},
    [0xB2] = {INS_OR, AM_R_R, A, D, CT_NONE, 0},
    [0xB3] = {INS_OR, AM_R_R, A, E, CT_NONE, 0},
    [0xB4] = {INS_OR, AM_R_R, A, H, CT_NONE, 0},
    [0xB5] = {INS_OR, AM_R_R, A, L, CT_NONE, 0},
    [0xB6] = {INS_OR, AM_R_MR, A, HL, CT_NONE, 0},
    [0xB7] = {INS_OR, AM_R_R, A, A, CT_NONE, 0},
    [0xB8] = {INS_CP, AM_R_R, A, B, CT_NONE, 0},
    [0xB9] = {INS_CP, AM_R_R, A, C, CT_NONE, 0},
    [0xBA] = {INS_CP, AM_R_R, A, D, CT_NONE, 0},
    [0xBB] = {INS_CP, AM_R_R, A, E, CT_NONE, 0},
    [0xBC] = {INS_CP, AM_R_R, A, H, CT_NONE, 0},
    [0xBD] = {INS_CP, AM_R_R, A, L, CT_NONE, 0},
    [0xBE] = {INS_CP, AM_R_MR, A, HL, CT_NONE, 0},
    [0xBF] = {INS_CP, AM_R_R, A, A, CT_NONE, 0},

    [0xC0] = {INS_RET, AM_IMP, NONE, NONE, CT_NZ, 0},
    [0xC1] = {INS_POP, AM_R, BC, NONE, CT_NONE, 0},
    [0xC2] = {INS_JP, AM_D16, NONE, NONE, CT_NZ, 0},
    [0xC3] = {INS_JP, AM_D16, NONE, NONE, CT_NONE, 0},
    [0xC4] = {INS_CALL, AM_D16, NONE, NONE, CT_NZ, 0},
    [0xC5] = {INS_PUSH, AM_R, BC, NONE, CT_NONE, 0},
    [0xC6] = {INS_ADD, AM_R_D8, A, NONE, CT_NONE, 0},
    [0xC7] = {INS_RST, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0xC8] = {INS_RET, AM_IMP, NONE, NONE, CT_Z, 0},
    [0xC9] = {INS_RET, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0xCA] = {INS_JP, AM_D16, NONE, NONE, CT_Z, 0},
    [0xCB] = {INS_CB, AM_D8, NONE, NONE, CT_NONE, 0},
    [0xCC] = {INS_CALL, AM_D16, NONE, NONE, CT_Z, 0},
    [0xCD] = {INS_CALL, AM_D16, NONE, NONE, CT_NONE, 0},
    [0xCE] = {INS_ADC, AM_R_D8, A, NONE, CT_NONE, 0},
    [0xCF] = {INS_RST, AM_IMP, NONE, NONE, CT_NONE, 0x08},

    [0xD0] = {INS_RET, AM_IMP, NONE, NONE, CT_NC, 0},
    [0xD1] = {INS_POP, AM_R, DE, NONE, CT_NONE, 0},
    [0xD2] = {INS_JP, AM_D16, NONE, NONE, CT_NC, 0},
    [0xD4] = {INS_CALL, AM_D16, NONE, NONE, CT_NC, 0},
    [0xD5] = {INS_PUSH, AM_R, DE, NONE, CT_NONE, 0},
    [0xD6] = {INS_SUB, AM_R_D8, A, NONE, CT_NONE, 0},
    [0xD7] = {INS_RST, AM_IMP, NONE, NONE, CT_NONE, 0x10},
    [0xD8] = {INS_RET, AM_IMP, NONE, NONE, CT_C, 0},
    [0xD9] = {INS_RETI, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0xDA] = {INS_JP, AM_D16, NONE, NONE, CT_C, 0},
    [0xDC] = {INS_CALL, AM_D16, NONE, NONE, CT_C, 0},
    [0xDE] = {INS_SBC, AM_R_D8, A, NONE, CT_NONE, 0},
    [0xDF] = {INS_RST, AM_IMP, NONE, NONE, CT_NONE, 0x18},

    [0xE0] = {INS_LDH, AM_A8_R, NONE, A, CT_NONE, 0},
    [0xE1] = {INS_POP, AM_R, HL, NONE, CT_NONE, 0},
    [0xE2] = {INS_LD, AM_MR_R, C, A, CT_NONE, 0},
    [0xE5] = {INS_PUSH, AM_R, HL, NONE, CT_NONE, 0},
    [0xE6] = {INS_AND, AM_R_D8, A, NONE, CT_NONE, 0},
    [0xE7] = {INS_RST, AM_IMP, NONE, NONE, CT_NONE, 0x20},
    [0xE8] = {INS_ADD, AM_R_D8, SP, NONE, CT_NONE, 0},
    [0xE9] = {INS_JP, AM_R, HL, NONE, CT_NONE, 0},
    [0xEA] = {INS_LD, AM_A16_R, NONE, A, CT_NONE, 0},
    [0xEE] = {INS_XOR, AM_R_D8, A, NONE, CT_NONE, 0},
    [0xEF] = {INS_RST, AM_IMP, NONE, NONE, CT_NONE, 0x28},

    [0xF0] = {INS_LDH, AM_R_A8, A, NONE, CT_NONE, 0},
    [0xF1] = {INS_POP, AM_R, AF, NONE, CT_NONE, 0,},
    [0xF2] = {INS_LD, AM_R_MR, A, C, CT_NONE, 0},
    [0xF3] = {INS_DI, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0xF5] = {INS_PUSH, AM_R, AF, NONE, CT_NONE, 0},
    [0xF6] = {INS_OR, AM_R_D8, A, NONE, CT_NONE, 0},
    [0xF7] = {INS_RST, AM_IMP, NONE, NONE, CT_NONE, 0x30},
    [0xF8] = {INS_LD, AM_HL_SPR, HL, SP, CT_NONE, 0},
    [0xF9] = {INS_LD, AM_R_R, SP, HL, CT_NONE, 0},
    [0xFA] = {INS_LD, AM_R_A16, A, NONE, CT_NONE, 0},
    [0xFB] = {INS_EI, AM_IMP, NONE, NONE, CT_NONE, 0},
    [0xFE] = {INS_CP, AM_R_D8, A, NONE, CT_NONE, 0},
    [0xFF] = {INS_RST, AM_IMP, NONE, NONE, CT_NONE, 0x38}
};

u16 get_register(CPU* cpu, reg_type reg) {
    switch(reg) {
        case NONE:
            return 0;
        case A:
            return cpu->a;
        case F:
            return cpu->f;
        case B:
            return cpu->a;
        case C:
            return cpu->a;
        case D:
            return cpu->a;
        case E:
            return cpu->a;
        case H:
            return cpu->a;
        case L:
            return cpu->a;
        case AF:
            return cpu->af;
        case BC:
            return cpu->bc;
        case DE:
            return cpu->de;
        case HL:
            return cpu->hl;
        case SP:
            return cpu->SP;
        //suppressing warnings...
        case PC:
            return 0;
        default:
            return 0;
    }
}